name: Build surfer & surver

on:
  push:
    tags:
      - "build-*"

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          fetch-tags: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-dev libxkbcommon-dev libwayland-dev \
            libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build surver and surfer
        run: cargo build --release --locked -p surver -p surfer

      - name: Package
        run: |
          mkdir -p surfer-suite-linux-x86_64/bin
          cp target/release/surfer target/release/surver surfer-suite-linux-x86_64/bin/
          tar czf surfer-suite-linux-x86_64.tar.gz surfer-suite-linux-x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: surfer-suite-linux-x86_64
          path: surfer-suite-linux-x86_64.tar.gz

  release:
    needs: [build-linux-x86_64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: surfer-suite-linux-x86_64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: surfer-suite-linux-x86_64.tar.gz
